### ISSUE TITLE
feat: when reloading code with ctrl + s the window is still being focused

### ISSUE THREAD

**Issue by amyspark-ng** [lajbel/kaplay#3]
preventing you from doing actions in your game as soon as you reload, kinda annoying

**Comment by lajbel** [comment]
maybe a config flag for this? or should be the default behaviour? Because normally I don't want my game being focused while I'm for example editing UI stuff and I only want to see changes

**Comment by amyspark-ng** [comment]
Really what's happening (at least to me) is that sometimes it doesn't unfocus the coding windows properly, i think it's when you click to focus BEFORE the game loades, so there's that

**Comment by lajbel** [comment]
I will put the behaviour of autofocus by default, if someone doesn't want it, you can use
```js
kaboom({ focus: false })
```

**Comment by lajbel** [comment]
fixed on: b5fa6e182d2f34c99ff2b7172e9e568570e7f929
